export const TIME = 'TIME';

export const RSVP_CHECKBOX_CHANGED = 'RSVP_CHECKBOX_CHANGED';
export const RSVP_COMMENTS_CHANGED = 'RSVP_COMMENTS_CHANGED';
export const RSVP_PHONE_CHANGED = 'RSVP_PHONE_CHANGED';
export const RSVP_EMAIL_CHANGED = 'RSVP_EMAIL_CHANGED';
export const RSVP_LAST_CHANGED = 'RSVP_LAST_CHANGED';
export const RSVP_FIRST_CHANGED = 'RSVP_FIRST_CHANGED';
