export const SPINNER_UPDATE = 'SPINNER_UPDATE';
export const ERROR_UPDATE = 'ERROR_UPDATE';

export const RSVP_FIRST_UPDATE = 'RSVP_FIRST_UPDATE';
export const RSVP_LAST_UPDATE = 'RSVP_LAST_UPDATE';
export const RSVP_EMAIL_UPDATE = 'RSVP_EMAIL_UPDATE';
export const RSVP_PHONE_UPDATE = 'RSVP_PHONE_UPDATE';
export const RSVP_COMMENTS_UPDATE = 'RSVP_COMMENTS_UPDATE';
export const RSVP_VEGGIE_UPDATE = 'RSVP_VEGGIE_UPDATE';
export const SHOW_COMING_FORM = 'SHOW_COMING_FORM';
export const SHOW_NOT_COMING_FORM = 'SHOW_NOT_COMING_FORM';
export const COMING_SUBMITTED = 'COMING_SUBMITTED';
export const NOT_COMMENTS_UPDATE = 'NOT_COMMENTS_UPDATE';
export const NOT_EMAIL_UPDATE = 'NOT_EMAIL_UPDATE';
export const NOT_LAST_UPDATE = 'NOT_LAST_UPDATE';
export const NOT_FIRST_UPDATE = 'NOT_FIRST_UPDATE';

export const GUESTS_FETCH_SUCCESS = 'GUESTS_FETCH_SUCCESS';
export const NOT_COMING_FETCH_SUCCESS = 'NOT_COMING_FETCH_SUCCESS';
export const SHOW_COMING_GUESTS = 'SHOW_COMING_GUESTS';
export const SHOW_NOT_COMING_GUESTS = 'SHOW_NOT_COMING_GUESTS';
export const SHOW_BOTH_GUESTS = 'SHOW_BOTH_GUESTS';
export const LOGIN_EMAIL_UPDATE = 'LOGIN_EMAIL_UPDATE';
export const LOGIN_PASSWORD_UPDATE = 'LOGIN_PASSWORD_UPDATE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const NOT_COMING_SUBMITTED = 'NOT_COMING_SUBMITTED';
